### ISSUE TITLE
Filters to manipulate register_post_type arguments

### ISSUE THREAD

**Issue by timothy-h** [miya0001/tinymce-templates#10]
The current menu_position is hard-coded to 100. I have many sidebar items and I'd like to change this to a more appropriate position, like 64 (after Appearance but before Plugins). I also have several tiers of users and would like to change the capabilities. I managed to do this by:

1. Changing `TinyMCE_Templates::register_post_type` to public
2. Changing the direct call to register_post_type on line 119 to a filter:
`add_filter( 'init', array( $this, 'register_post_type' ), 20 );`
3. Removing the `capability_type` parameter from the arguments and adding `'capabilities' => apply_filters( 'tinymce_templates_capabilities', array() ),`
4. Change the value of `menu_position` to:
`apply_filters( 'tinymce_templates_menu_position', 64 )`

Once these changes have been made, it's trivial to add filters to a theme or plugin to alter the menu position and manage capabilities on a more granular level.

**Comment by miya0001** [comment]
Please send pull request. :smile:

**Comment by timothy-h** [comment]
I've linked to the a tar in the other issue. Sorry about that, I've never made a pull request before. I'll make one the next time I have a change to this plugin. I may update the capability argument, I haven't really shaken that one down yet for default user roles.
