### ISSUE TITLE
Replace register function with __construct

### ISSUE THREAD

**Issue by timothy-h** [miya0001/tinymce-templates#11]
The [`__construct` function](http://php.net/manual/en/language.oop5.decon.php) of a class gets called automatically when a class is instantiated; it's the class's constructor. If you renamed `public function register` to `public function __construct` you could eliminate the call to `register` immediately after creating a singleton for `TinyMCE_Templates`.

**Comment by miya0001** [comment]
Thanks for advise.
But `register()` need for backward compatibility.
