### ISSUE TITLE
Language pack - Chinese

### ISSUE THREAD

**Issue by Riant** [miya0001/tinymce-templates#12]
Thanks for your great work, I made a Chinese translate for this plugin, wish you like it and include it to your next version.

Download po/mo files on there https://www.dropbox.com/sh/iye25b9ka1arfvo/AAA-tU2iRXr3QmVl2DHyCdaFa?dl=0

**Comment by miya0001** [comment]
Thanks for translation! :)
https://github.com/miya0001/tinymce-templates/commit/db24c44b784d2cb83360f7376f2667df096ef9f3
