### ISSUE TITLE
Remove bad tests

### ISSUE THREAD

**Issue by timothy-h** [miya0001/tinymce-templates#14]
The GitHub client is pretty buggy on Windows and I cannot sync my changes. You need to remove `function media_buttons_01()`, `function media_buttons_02()` and `function media_buttons_03()` from tests/test-tinymce-templates.php. The commit I made works perfectly, the tests themselves are bad.

**Comment by timothy-h** [comment]
Can you please remove these outdated tests and merge my pull request? The request fixes many critical issues with this plugin.

**Comment by miya0001** [comment]
Sorry for late. :)

It doesn't make sense because git client doesn't care about phpunit.

> The GitHub client is pretty buggy on Windows and I cannot sync my changes. 

We should add/update new tests and I won't do just removing tests.

**Comment by timothy-h** [comment]
The tests in question look for attributes that I've removed because those attributes are no longer used.

**Comment by miya0001** [comment]
Could you write test?
I have many deadlines so I am hoping doing tests your pull request automatically.
I have to write tests If you can't write tests, but I am thinking that your pull request isn't important for me.

**Comment by timothy-h** [comment]
This is your plugin. I've spent hours fixing your bugs and I have deadlines of my own. I've told you that your tests no longer serve a purpose. What would new tests check for?

And where is your pride in your work? How can you dismiss this as unimportant when multiple people are reporting this issue and a working patch has been submitted? I'm not asking you to spend days rewriting this plugin, I'm asking you to take maybe 5-10 minutes to just look at my pull request, confirm that it actually does what it's supposed to do, remove the old tests that don't do anything, and merge this.

**Comment by miya0001** [comment]
I wonder why don't you update tests. It's need just updating html outputs in the test.
And I have never used plugin that generates editor dynamically like wpml.
So I can't do test with whole plugins.

**Comment by timothy-h** [comment]
This is your plugin. I've spent hours fixing your bugs and I have deadlines of my own. I've told you that your tests no longer serve a purpose. What would new tests check for?

**Comment by miya0001** [comment]
You have changed html output at `media_buttons()` so you should update checking html source in the test.

https://github.com/miya0001/tinymce-templates/blob/master/tests/test-tinymce-templates.php#L107
https://github.com/miya0001/tinymce-templates/blob/master/tests/test-tinymce-templates.php#L117
https://github.com/miya0001/tinymce-templates/blob/master/tests/test-tinymce-templates.php#L128

I am thinking we should update tests html output without  `id` attributes.
I want to check function parameter.

Other contributors had sent a pull request with updating tests like following.
https://github.com/miya0001/tinymce-templates/pull/15

It's my plugin, but it's your issue isn't it?
Is it bugs? I am thinking I don't need support additional editor.
But I got a better looking patch from you and I was thinking merge it with a little fix.

Actually your patch will add button to all editor in the post screen.
Are you thinking all user need it?
If some user say "we don't need it", we should consider about it.

And again I had never used plugin that would add a additional editor.
So if you want to support them I am hoping I need your help.

One more thing, I found a bug in your pull request.
`init` is not `filter` so it is `action`.

We aren't perfect, so we should discus calmly you shouldn't get angry.
