### ISSUE TITLE
Missing image replacement buttons

### ISSUE THREAD

**Issue by dowen121** [miya0001/tinymce-templates#21]
Hello,

Thanks for the fantastic plugin but I have a problem with the template insert and i'm hoping you can help.

When inserting a template into the editor we want to be able to replace the image by clicking on the "Replace" button when editing the image. This is not present when using any of the templates.

Please see this image demonstrating the problem http://imgur.com/a/WQ173

Is this easily solved?

Many thanks,
Daf

**Comment by miya0001** [comment]
Is the problem caused by this plugin?
Please try to deactivate another plugins.

**Comment by dowen121** [comment]
Deactivating all plugins did not solve my issue.

The same issue is present when editing an existing TinyMCE template.
