### ISSUE TITLE
Plugin doesn't work with editors generated by certain other plugins.

### ISSUE THREAD

**Issue by timothy-h** [miya0001/tinymce-templates#9]
I wrote up a detailed overview [on the Wordpress forum](https://wordpress.org/support/topic/template-button-for-custom-field-editor?replies=4) for this plugin, containing code and line numbers to change so that the issues I brought up are resolved. Can you please apply these changes to this plugin?

**Comment by miya0001** [comment]
I want to try it.
Can you send pull request?

**Comment by timothy-h** [comment]
I've never done a pull request before, but I tarred up everything I've done to this plugin and [uploaded it here](http://www.ashworthcreative.com/dev/tinymce-templates.tar). I really think you should reconsider the constructor, I don't see how that would affect backwards compatibility. The function was only being called once, as soon as the script was processed. It would never be called again.
